/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableroRouteImport } from './routes/tablero'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as NuevaTareaRouteImport } from './routes/nueva-tarea'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FocoRouteImport } from './routes/foco'
import { Route as CrearTareaRouteImport } from './routes/crear-tarea'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalIndexRouteImport } from './routes/legal.index'
import { Route as AjustesIndexRouteImport } from './routes/ajustes.index'
import { Route as LegalTerminosRouteImport } from './routes/legal.terminos'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as LegalLicenciasRouteImport } from './routes/legal.licencias'
import { Route as AjustesProductividadRouteImport } from './routes/ajustes.productividad'
import { Route as AjustesOrganizacionRouteImport } from './routes/ajustes.organizacion'
import { Route as AjustesNotificacionesRouteImport } from './routes/ajustes.notificaciones'
import { Route as AjustesIaRouteImport } from './routes/ajustes.ia'
import { Route as AjustesCalendarioRouteImport } from './routes/ajustes.calendario'
import { Route as AjustesAparienciaRouteImport } from './routes/ajustes.apariencia'
import { Route as AjustesAcercaDeRouteImport } from './routes/ajustes.acerca-de'

const TableroRoute = TableroRouteImport.update({
  id: '/tablero',
  path: '/tablero',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaTareaRoute = NuevaTareaRouteImport.update({
  id: '/nueva-tarea',
  path: '/nueva-tarea',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FocoRoute = FocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearTareaRoute = CrearTareaRouteImport.update({
  id: '/crear-tarea',
  path: '/crear-tarea',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalIndexRoute = LegalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LegalRoute,
} as any)
const AjustesIndexRoute = AjustesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AjustesRoute,
} as any)
const LegalTerminosRoute = LegalTerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => LegalRoute,
} as any)
const LegalLicenciasRoute = LegalLicenciasRouteImport.update({
  id: '/licencias',
  path: '/licencias',
  getParentRoute: () => LegalRoute,
} as any)
const AjustesProductividadRoute = AjustesProductividadRouteImport.update({
  id: '/productividad',
  path: '/productividad',
  getParentRoute: () => AjustesRoute,
} as any)
const AjustesOrganizacionRoute = AjustesOrganizacionRouteImport.update({
  id: '/organizacion',
  path: '/organizacion',
  getParentRoute: () => AjustesRoute,
} as any)
const AjustesNotificacionesRoute = AjustesNotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => AjustesRoute,
} as any)
const AjustesIaRoute = AjustesIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AjustesRoute,
} as any)
const AjustesCalendarioRoute = AjustesCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AjustesRoute,
} as any)
const AjustesAparienciaRoute = AjustesAparienciaRouteImport.update({
  id: '/apariencia',
  path: '/apariencia',
  getParentRoute: () => AjustesRoute,
} as any)
const AjustesAcercaDeRoute = AjustesAcercaDeRouteImport.update({
  id: '/acerca-de',
  path: '/acerca-de',
  getParentRoute: () => AjustesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/crear-tarea': typeof CrearTareaRoute
  '/foco': typeof FocoRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/nueva-tarea': typeof NuevaTareaRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tablero': typeof TableroRoute
  '/ajustes/acerca-de': typeof AjustesAcercaDeRoute
  '/ajustes/apariencia': typeof AjustesAparienciaRoute
  '/ajustes/calendario': typeof AjustesCalendarioRoute
  '/ajustes/ia': typeof AjustesIaRoute
  '/ajustes/notificaciones': typeof AjustesNotificacionesRoute
  '/ajustes/organizacion': typeof AjustesOrganizacionRoute
  '/ajustes/productividad': typeof AjustesProductividadRoute
  '/legal/licencias': typeof LegalLicenciasRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/ajustes/': typeof AjustesIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/crear-tarea': typeof CrearTareaRoute
  '/foco': typeof FocoRoute
  '/login': typeof LoginRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/nueva-tarea': typeof NuevaTareaRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tablero': typeof TableroRoute
  '/ajustes/acerca-de': typeof AjustesAcercaDeRoute
  '/ajustes/apariencia': typeof AjustesAparienciaRoute
  '/ajustes/calendario': typeof AjustesCalendarioRoute
  '/ajustes/ia': typeof AjustesIaRoute
  '/ajustes/notificaciones': typeof AjustesNotificacionesRoute
  '/ajustes/organizacion': typeof AjustesOrganizacionRoute
  '/ajustes/productividad': typeof AjustesProductividadRoute
  '/legal/licencias': typeof LegalLicenciasRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/ajustes': typeof AjustesIndexRoute
  '/legal': typeof LegalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/crear-tarea': typeof CrearTareaRoute
  '/foco': typeof FocoRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/nueva-tarea': typeof NuevaTareaRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/registro': typeof RegistroRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tablero': typeof TableroRoute
  '/ajustes/acerca-de': typeof AjustesAcercaDeRoute
  '/ajustes/apariencia': typeof AjustesAparienciaRoute
  '/ajustes/calendario': typeof AjustesCalendarioRoute
  '/ajustes/ia': typeof AjustesIaRoute
  '/ajustes/notificaciones': typeof AjustesNotificacionesRoute
  '/ajustes/organizacion': typeof AjustesOrganizacionRoute
  '/ajustes/productividad': typeof AjustesProductividadRoute
  '/legal/licencias': typeof LegalLicenciasRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/ajustes/': typeof AjustesIndexRoute
  '/legal/': typeof LegalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/calendario'
    | '/crear-tarea'
    | '/foco'
    | '/legal'
    | '/login'
    | '/mi-cuenta'
    | '/nueva-tarea'
    | '/recuperar-contrasena'
    | '/registro'
    | '/reset-password'
    | '/tablero'
    | '/ajustes/acerca-de'
    | '/ajustes/apariencia'
    | '/ajustes/calendario'
    | '/ajustes/ia'
    | '/ajustes/notificaciones'
    | '/ajustes/organizacion'
    | '/ajustes/productividad'
    | '/legal/licencias'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/ajustes/'
    | '/legal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/crear-tarea'
    | '/foco'
    | '/login'
    | '/mi-cuenta'
    | '/nueva-tarea'
    | '/recuperar-contrasena'
    | '/registro'
    | '/reset-password'
    | '/tablero'
    | '/ajustes/acerca-de'
    | '/ajustes/apariencia'
    | '/ajustes/calendario'
    | '/ajustes/ia'
    | '/ajustes/notificaciones'
    | '/ajustes/organizacion'
    | '/ajustes/productividad'
    | '/legal/licencias'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/ajustes'
    | '/legal'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/calendario'
    | '/crear-tarea'
    | '/foco'
    | '/legal'
    | '/login'
    | '/mi-cuenta'
    | '/nueva-tarea'
    | '/recuperar-contrasena'
    | '/registro'
    | '/reset-password'
    | '/tablero'
    | '/ajustes/acerca-de'
    | '/ajustes/apariencia'
    | '/ajustes/calendario'
    | '/ajustes/ia'
    | '/ajustes/notificaciones'
    | '/ajustes/organizacion'
    | '/ajustes/productividad'
    | '/legal/licencias'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/ajustes/'
    | '/legal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  CrearTareaRoute: typeof CrearTareaRoute
  FocoRoute: typeof FocoRoute
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  MiCuentaRoute: typeof MiCuentaRoute
  NuevaTareaRoute: typeof NuevaTareaRoute
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  RegistroRoute: typeof RegistroRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TableroRoute: typeof TableroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablero': {
      id: '/tablero'
      path: '/tablero'
      fullPath: '/tablero'
      preLoaderRoute: typeof TableroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-tarea': {
      id: '/nueva-tarea'
      path: '/nueva-tarea'
      fullPath: '/nueva-tarea'
      preLoaderRoute: typeof NuevaTareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foco': {
      id: '/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof FocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-tarea': {
      id: '/crear-tarea'
      path: '/crear-tarea'
      fullPath: '/crear-tarea'
      preLoaderRoute: typeof CrearTareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/': {
      id: '/legal/'
      path: '/'
      fullPath: '/legal/'
      preLoaderRoute: typeof LegalIndexRouteImport
      parentRoute: typeof LegalRoute
    }
    '/ajustes/': {
      id: '/ajustes/'
      path: '/'
      fullPath: '/ajustes/'
      preLoaderRoute: typeof AjustesIndexRouteImport
      parentRoute: typeof AjustesRoute
    }
    '/legal/terminos': {
      id: '/legal/terminos'
      path: '/terminos'
      fullPath: '/legal/terminos'
      preLoaderRoute: typeof LegalTerminosRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/licencias': {
      id: '/legal/licencias'
      path: '/licencias'
      fullPath: '/legal/licencias'
      preLoaderRoute: typeof LegalLicenciasRouteImport
      parentRoute: typeof LegalRoute
    }
    '/ajustes/productividad': {
      id: '/ajustes/productividad'
      path: '/productividad'
      fullPath: '/ajustes/productividad'
      preLoaderRoute: typeof AjustesProductividadRouteImport
      parentRoute: typeof AjustesRoute
    }
    '/ajustes/organizacion': {
      id: '/ajustes/organizacion'
      path: '/organizacion'
      fullPath: '/ajustes/organizacion'
      preLoaderRoute: typeof AjustesOrganizacionRouteImport
      parentRoute: typeof AjustesRoute
    }
    '/ajustes/notificaciones': {
      id: '/ajustes/notificaciones'
      path: '/notificaciones'
      fullPath: '/ajustes/notificaciones'
      preLoaderRoute: typeof AjustesNotificacionesRouteImport
      parentRoute: typeof AjustesRoute
    }
    '/ajustes/ia': {
      id: '/ajustes/ia'
      path: '/ia'
      fullPath: '/ajustes/ia'
      preLoaderRoute: typeof AjustesIaRouteImport
      parentRoute: typeof AjustesRoute
    }
    '/ajustes/calendario': {
      id: '/ajustes/calendario'
      path: '/calendario'
      fullPath: '/ajustes/calendario'
      preLoaderRoute: typeof AjustesCalendarioRouteImport
      parentRoute: typeof AjustesRoute
    }
    '/ajustes/apariencia': {
      id: '/ajustes/apariencia'
      path: '/apariencia'
      fullPath: '/ajustes/apariencia'
      preLoaderRoute: typeof AjustesAparienciaRouteImport
      parentRoute: typeof AjustesRoute
    }
    '/ajustes/acerca-de': {
      id: '/ajustes/acerca-de'
      path: '/acerca-de'
      fullPath: '/ajustes/acerca-de'
      preLoaderRoute: typeof AjustesAcercaDeRouteImport
      parentRoute: typeof AjustesRoute
    }
  }
}

interface AjustesRouteChildren {
  AjustesAcercaDeRoute: typeof AjustesAcercaDeRoute
  AjustesAparienciaRoute: typeof AjustesAparienciaRoute
  AjustesCalendarioRoute: typeof AjustesCalendarioRoute
  AjustesIaRoute: typeof AjustesIaRoute
  AjustesNotificacionesRoute: typeof AjustesNotificacionesRoute
  AjustesOrganizacionRoute: typeof AjustesOrganizacionRoute
  AjustesProductividadRoute: typeof AjustesProductividadRoute
  AjustesIndexRoute: typeof AjustesIndexRoute
}

const AjustesRouteChildren: AjustesRouteChildren = {
  AjustesAcercaDeRoute: AjustesAcercaDeRoute,
  AjustesAparienciaRoute: AjustesAparienciaRoute,
  AjustesCalendarioRoute: AjustesCalendarioRoute,
  AjustesIaRoute: AjustesIaRoute,
  AjustesNotificacionesRoute: AjustesNotificacionesRoute,
  AjustesOrganizacionRoute: AjustesOrganizacionRoute,
  AjustesProductividadRoute: AjustesProductividadRoute,
  AjustesIndexRoute: AjustesIndexRoute,
}

const AjustesRouteWithChildren =
  AjustesRoute._addFileChildren(AjustesRouteChildren)

interface LegalRouteChildren {
  LegalLicenciasRoute: typeof LegalLicenciasRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  LegalTerminosRoute: typeof LegalTerminosRoute
  LegalIndexRoute: typeof LegalIndexRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalLicenciasRoute: LegalLicenciasRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  LegalTerminosRoute: LegalTerminosRoute,
  LegalIndexRoute: LegalIndexRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  CrearTareaRoute: CrearTareaRoute,
  FocoRoute: FocoRoute,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  MiCuentaRoute: MiCuentaRoute,
  NuevaTareaRoute: NuevaTareaRoute,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  RegistroRoute: RegistroRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TableroRoute: TableroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
