/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TableroRouteImport } from './routes/tablero'
import { Route as NuevaTareaRouteImport } from './routes/nueva-tarea'
import { Route as FocoRouteImport } from './routes/foco'
import { Route as CrearTareaRouteImport } from './routes/crear-tarea'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'

const TableroRoute = TableroRouteImport.update({
  id: '/tablero',
  path: '/tablero',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaTareaRoute = NuevaTareaRouteImport.update({
  id: '/nueva-tarea',
  path: '/nueva-tarea',
  getParentRoute: () => rootRouteImport,
} as any)
const FocoRoute = FocoRouteImport.update({
  id: '/foco',
  path: '/foco',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearTareaRoute = CrearTareaRouteImport.update({
  id: '/crear-tarea',
  path: '/crear-tarea',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/crear-tarea': typeof CrearTareaRoute
  '/foco': typeof FocoRoute
  '/nueva-tarea': typeof NuevaTareaRoute
  '/tablero': typeof TableroRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/crear-tarea': typeof CrearTareaRoute
  '/foco': typeof FocoRoute
  '/nueva-tarea': typeof NuevaTareaRoute
  '/tablero': typeof TableroRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/crear-tarea': typeof CrearTareaRoute
  '/foco': typeof FocoRoute
  '/nueva-tarea': typeof NuevaTareaRoute
  '/tablero': typeof TableroRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/crear-tarea'
    | '/foco'
    | '/nueva-tarea'
    | '/tablero'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/crear-tarea'
    | '/foco'
    | '/nueva-tarea'
    | '/tablero'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/crear-tarea'
    | '/foco'
    | '/nueva-tarea'
    | '/tablero'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CrearTareaRoute: typeof CrearTareaRoute
  FocoRoute: typeof FocoRoute
  NuevaTareaRoute: typeof NuevaTareaRoute
  TableroRoute: typeof TableroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tablero': {
      id: '/tablero'
      path: '/tablero'
      fullPath: '/tablero'
      preLoaderRoute: typeof TableroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-tarea': {
      id: '/nueva-tarea'
      path: '/nueva-tarea'
      fullPath: '/nueva-tarea'
      preLoaderRoute: typeof NuevaTareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foco': {
      id: '/foco'
      path: '/foco'
      fullPath: '/foco'
      preLoaderRoute: typeof FocoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crear-tarea': {
      id: '/crear-tarea'
      path: '/crear-tarea'
      fullPath: '/crear-tarea'
      preLoaderRoute: typeof CrearTareaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CrearTareaRoute: CrearTareaRoute,
  FocoRoute: FocoRoute,
  NuevaTareaRoute: NuevaTareaRoute,
  TableroRoute: TableroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
